services:
  - type: web
    name: cookify
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
